"""Initial migration.

Revision ID: a183c01d9647
Revises: 
Create Date: 2020-11-04 19:02:08.730476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a183c01d9647'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('uri', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.String(length=10240), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('topic', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filetrack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filetrack')
    op.drop_table('article')
    # ### end Alembic commands ###
